### ISSUE TITLE
Git for beginners

### ISSUE THREAD

**Issue by cbahlai** [cbahlai/OSRR_course#11]
Spoon

**Comment by cbahlai** [comment]
Wow, was this a fever dream? I probably shouldn't make cryptic notes to myself so publicly.

**Comment by gedankenstuecke** [comment]
Haha, I thought it was a play on forks for your course :smiley:

**Comment by stephwright** [comment]
I was wondering what you were up to.

**Comment by cbahlai** [comment]
It must be. I just...woah.
