### ISSUE TITLE
additional reading for 'what is open science' 

### ISSUE THREAD

**Issue by gedankenstuecke** [cbahlai/OSRR_course#2]
Hey there,
great job so far! I'm not sure how you'd prefer to get contributions at this point. So I'll just use this to suggest a an additional reading resource for the first lesson. 

I think that "[When will ‘open science’ become simply ‘science’?](http://www.genomebiology.com/2015/16/1/101)" by Mick Watson is a really good primer. And it also gives some good motivation on why you should do "open" in the first place. :smile: 

Cheers,
Bastian

**Comment by cbahlai** [comment]
Thanks Bastian! I added it to the first lesson. Will get the students to read it!

**Comment by gedankenstuecke** [comment]
Great, thanks so much! :+1: 

Let me know if/how you want more input! :smile:

**Comment by stephwright** [comment]
I hadn't read that one yet, either!  Thanks @gedankenstuecke!
