### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by amandamiotto** [cbahlai/OSRR_course#29]
I don't actually have an issue, I just wanted to say that this has been a pleasure to read. I laughed so hard at the Data Sharing and Management Snafu in 3 Short Acts from NYU Health Sciences Library, and this whole guide was really simple to read (and fun). 

Thanks for writing it!
Amanda

**Comment by cbahlai** [comment]
Hi Amanda! Thanks so much- a (slightly) updated, more graphically schnazzy version of the course is available here: https://github.com/cbahlai/rqm-template
